services:
  backend:
    image: morgenpruefung/mp-backend
    restart: on-failure
    container_name: mp-backend
    ports:
      - "4242:4242"
    environment:
      - PORT=4242
      - FANCYANALYTICS_PROJECT_ID=
      - FANCYANALYTICS_API_KEY=
      - MONGODB_URI=
    networks:
      - mp-network
    depends_on:
      - frontend

  frontend:
    image: morgenpruefung/mp-frontend
    restart: on-failure
    container_name: mp-frontend
    ports:
      - "4343:80"
    networks:
      - mp-network

  watchtower:
    image: containrrr/watchtower
    container_name: mp-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: backend frontend
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300 # in seconds (here: 5min)
    networks:
      - mp-network

networks:
  mp-network:
    driver: bridge